version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      major:
        update-types:
          - "major"
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
